paths:
    rgb_data_dirs: "./data/optical/test_cut/test_1/rgb"
    NIRS_data_dirs: "./data/optical/test_cut/test_1/NIRS"
    export_dir: "./data/optical/test_cut/triplets"
    export_match_dir: "./data/optical/test_cut/test_1/matches"
    # rgb_data_dirs: "./data/optical/test_full/test_1/rgb"
    # NIRS_data_dirs: "./data/optical/test_full/test_1/NIRS"
    # export_dir: "./data/optical/test_full/triplets"
    # export_match_dir: "./data/optical/test_full/test_1/matches"
params:
    keypoint_extractor: "SIFT"
    # distance in pixel
    keypoint_dist_threshold: 3
    patch_size: 128
    transformation_list: ['zoom', 'rotation', 'translation']
    predefined_angle_degrees: [5, 10, 15]
    predefined_zoom_factors: [0.9, 0.95, 1.05, 1.1, 1.15]
    predefined_translation_pixels: [8]
